version: '2'

volumes:
  node_modules:
  yarn_cache:

services:
  app:
    image: node:7.10
    working_dir: /app
    ports:
      - 3000:3000
    command: "webpack-dev-server"
    environment: &env
      RPC_HOST: testrpc
      PATH: '/app/node_modules/.bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    depends_on:
      - testrpc
    volumes: &volumes
      - './:/app'
      - 'node_modules:/app/node_modules'
      - 'yarn_cache:/usr/local/share/.cache/yarn/v1'

  testrpc:
    image: provivus/testrpc
    command: testrpc -a 50
    ports:
      - 8545:8545
